# Generated by Django 5.0.2 on 2024-02-15 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='audio_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
