# Generated by Django 5.0.2 on 2024-02-16 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_book_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dictation',
        ),
        migrations.DeleteModel(
            name='Sentence',
        ),
        migrations.DeleteModel(
            name='Word',
        ),
        migrations.RemoveField(
            model_name='book',
            name='file',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
